In [1]:
import pandas as pd

data = pd.read_csv(r"data\winequality-red.csv")
data.head(5)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [2]:
data.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [3]:
data.corr().style.background_gradient(cmap='coolwarm')

In [4]:
import numpy as np
d_arr = np.asarray(data)
X = d_arr[:, :11]
y = d_arr[:, -1]
y = y.reshape(-1,1)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()

In [7]:
lin_reg.fit(X_train, y_train)

LinearRegression()

In [8]:
y_pred = lin_reg.predict(X_test)

In [9]:
lin_reg.coef_

array([[ 4.12835075e-02, -1.14952802e+00, -1.77927063e-01,
         2.78700036e-02, -1.87340739e+00,  2.68362616e-03,
        -2.77748370e-03, -3.15166657e+01, -2.54486051e-01,
         9.24040106e-01,  2.67797417e-01]])

In [10]:
lin_reg.intercept_

array([34.99871063])

In [17]:
from sklearn.metrics import mean_squared_error, root_mean_squared_error, mean_absolute_error, mean_absolute_percentage_error
print("Mean squared error: ", mean_squared_error(y_pred, y_test))
print("Mean absolute error: ", mean_absolute_error(y_pred, y_test))
print("Root mean squared error: ", root_mean_squared_error(y_pred, y_test))
print(f"Mean absolute percentage error: {mean_absolute_percentage_error(y_pred, y_test)*100}%")
print("R score: ", lin_reg.score(X_test, y_test))

Mean squared error:  0.38447119782012334
Mean absolute error:  0.4696330928661091
Root mean squared error:  0.6200574149384259
Mean absolute percentage error: 8.26871538970771%
R score:  0.3283887639580241